### PR TITLE
Only check return type if both superclass and subclass have a type-hint

### LINKED ISSUE #83: `sub_return` is required if `super_return` is specified
Currently, subclasses are required to have a return type-hint if the superclass defines one.

```python
import overrides

class SuperClass(overrides.EnforceOverrides):
    def foo(self) -> int:
        return 1

class SubClass(SuperClass):
    @overrides.overrides
    def foo(self):
        return 2

# TypeError: SubClass.foo: return type `None` is not a `<class 'int'>`.
```

This is because `and sub_return is not None` is missing on the following line.

https://github.com/mkorpela/overrides/blob/deb0f3f291d8797e7f1a8f3137ad6e8e6e3898cf/overrides/signature.py#L286-L288

### PR DESCRIPTION
**Pull request by ashwin153**
- Closes #83.

### CODE REVIEW

**Comment by Victor333Huesca** [comment]
Hi,

Anything preventing this fix to be merged?
The issue it solves is quite frustrating and I would be glad to bump my codebase from 3.1 to 6.x
Also I tested locally and it seems to work.

Regard,
Victor

**Comment by ashwin153** [comment]
@mkorpela Any reason why this can't be merged?

**Comment by mkorpela** [comment]
@ashwin153 I think I did not do anything to this because the tests failed.

**Comment by mkorpela** [comment]
For some reason I do not either have possibility to re-run the tests..

**Comment by mkorpela** [comment]
I'll now merge this.

**Comment by mkorpela** [comment]
So reason is that tests fail: https://github.com/mkorpela/overrides/actions/runs/1144564995

**Pull request merged**
