### PR TITLE
Support for "final" keyword

### PR DESCRIPTION
**Pull request by leeopop**

### CODE REVIEW

**Comment by mkorpela** [comment]
Seems like the nightly python is broken. I'll rerun the tests tomorrow.

**Comment by leeopop** [comment]
The error msg says that certain opcodes are not in the dictionary.

**Comment by leeopop** [comment]
Saying that:

File "/home/travis/build/mkorpela/overrides/overrides/overrides.py", line 97, in _get_base_class_names
    if type(co.co_consts[oparg]) == str:
IndexError: tuple index out of range

**Comment by leeopop** [comment]
Does the original master branch works with nightly builds?

**Comment by leeopop** [comment]
[https://travis-ci.org/leeopop/overrides/builds/135377508](url)

I found that the master branch also fails on the nightly build.
I think that it would be better to remove night builds from the CI checklist 
or find other ways to identify superclasses w/o using the disassembler.

**Pull request merged**
