### PR TITLE
Ignore first parameter for non-static methods

### PR DESCRIPTION
**Pull request by ashwin153**
- Don't type check `self` or `cls` parameters.

### CODE REVIEW

**Comment by ashwin153** [comment]
Does not work on staticmethods.

**Comment by mkorpela** [comment]
I think _unbound_func(callable) returns if the method is boud or not

**Comment by mkorpela** [comment]
@ashwin153 you could try with that? I’ve already spent whole day with laptop so no juice left in me for coding right now.

**Comment by mkorpela** [comment]
Well maybe some juice.

**Comment by mkorpela** [comment]
I think I got the problem.
Normally we are checking the overrides in a situation where the method is still unbound. Thus it will not detect self or cls.

**Comment by mkorpela** [comment]
@ashwin153 could you review this?

**Comment by ashwin153** [comment]
Can you verify that `ensure_signature_is_compatible` works when `super_callable` and `sub_callable` are top-level functions.

```python
def sup(x: str) -> object:
  pass

def sub(x: object) -> str:
  pass

ensure_signature_is_compatible(sup, sub)
```

**Comment by ashwin153** [comment]
> I think _unbound_func(callable) returns if the method is boud or not

I was playing around with it this morning, and it didn't seem to be correctly determining whether or not it is a bound method.

**Comment by mkorpela** [comment]
@ashwin153 good points. Now I think I have the correct implementation. It has now also tests for static method detection.

**Comment by mkorpela** [comment]
I'll merge this. So we can go on.

**Pull request merged**
